### ISSUE TITLE
Only parse start data and repeat the results in sheet and doesnt get whole data from page.

### ISSUE THREAD

**Issue by shgupta008** [afkniladri/gibJustdialData#1]

**Comment by 0xNILADRI** [comment]
Recently Justdial switched to infinite scroll schema and unfortunately beautifulsoup only extracts once loaded data. To achieve this we would require a real instance of browser say, Selenium. Hate to let you down I'm a bit low on time. If you undertake this job and achieve the goal, do raise a PR.
