### ISSUE TITLE
Phone number not being extracted. Please Help! 

### ISSUE THREAD

**Issue by akhilkhemani** [afkniladri/gibJustdialData#2]
I tested your code.

Tried to extract data using the JD link :
https://www.justdial.com/Chandigarh/Curtain-Dealers/nct-10149922

The file generated (csv file) has all fields perfectly extracted except the phone number field....And that field is the most critical one for me. Can you please look into it and help me out.

[akhiltest.csv](https://github.com/afkniladri/gibJustdialData/files/9387287/akhiltest.csv)
[akhiltest2.csv](https://github.com/afkniladri/gibJustdialData/files/9387288/akhiltest2.csv)

**Comment by ggupta85** [comment]
Same issue. Kindly help resolve at the earliest.

**Comment by 0xNILADRI** [comment]
I am not actively contributing to the project right now. Kindly clone it and try to modify the source in order to work. Start with how to parse the scraped data. I think JD made changes to the website which led to this issue. Thanks, closing the issue now.
